### ISSUE TITLE
TypeError: 'dict_keys' object does not support indexing

### ISSUE THREAD

**Issue by passionaqua** [webgovernor/pykwiki#9]
Hi all, 
it's me, again. ^^

The last fix created, perhaps, a new issue!

```
[adrien@ArchPaw site_du_projet]$ pykwiki cache -f
Reading configuration from /home/adrien/Espace_Dev/Projets-multi/AnotherNotebook/site_du_projet/config.yaml
========================================
Caching source posts...
Caching: index.md
Saving to: /home/adrien/Espace_Dev/Projets-multi/AnotherNotebook/site_du_projet/docroot/index.html
Generating theme menu from links.yaml
Traceback (most recent call last):
  File "/usr/bin/pykwiki", line 254, in <module>
    command_cache(args)
  File "/usr/bin/pykwiki", line 136, in command_cache
    num_cached = ctrl.cache_posts(plist, force=force)
  File "/usr/lib/python3.4/site-packages/pykwiki/core.py", line 262, in cache_posts
    pg.save()
  File "/usr/lib/python3.4/site-packages/pykwiki/core.py", line 729, in save
    html = render_theme_template(conf.post_tpl, post=self)        
  File "/usr/lib/python3.4/site-packages/pykwiki/core.py", line 31, in render_theme_template
    **kwargs)
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/home/adrien/Espace_Dev/Projets-multi/AnotherNotebook/site_du_projet/themes/default/post.html", line 1, in <module>
    {% extends 'layout.html' %}
  File "/home/adrien/Espace_Dev/Projets-multi/AnotherNotebook/site_du_projet/themes/default/layout.html", line 114, in <module>
    {{ ctrl.theme_menu }}
  File "/usr/lib/python3.4/site-packages/jinja2/environment.py", line 397, in getattr
    return getattr(obj, attribute)
  File "/usr/lib/python3.4/site-packages/pykwiki/core.py", line 467, in theme_menu
    menu_links = get_clean_links(links)
  File "/usr/lib/python3.4/site-packages/pykwiki/core.py", line 447, in get_clean_links
    key = d.keys()[0]
TypeError: 'dict_keys' object does not support indexing
```

I hope you'll be able to fix it. :)

**Comment by webgovernor** [comment]
Pykwiki 1.1.1 should be available on PIP shortly. I'm not sure how I missed this issue ;)
